### ISSUE TITLE
Audit: PDM-009 - Error Handling in Chain Extension

### ISSUE THREAD

**Issue by ashneverdawn** [pendulum-chain/pendulum#259] opened 2023-07-05 14:02 UTC
Implementation of ChainExtension often utilizes `DispatchError::Other("Explanatory string")` error, which makes error handling difficult.

ID PDM-009
Scope Code Quality
Status New

**Description**
  The current implementation of ChainExtension frequently relies on the generic `DispatchError::Other()` error. This approach makes error handling challenging, particularly for developers working with smart contracts. The indiscriminate use of this error type makes it difficult to monitor and diagnose specific errors, impeding efficient troubleshooting and code improvement.

**Recommendation**
To improve error handling in the ChainExtension implementation, we recommend implementing a custom enum that covers all the required error types. This custom enum will provide a more structured approach to error handling by encapsulating specific errors and enabling precise identification and resolution of issues.
By implementing the custom enum and incorporating it into the RetVal result, developers will have access to more detailed error information, allowing them to effectively identify and handle different error scenarios. This approach enhances the overall robustness and maintainability of the codebase, as well as facilitates troubleshooting and future improvements.

**Comment by vadaynujra** [comment] 2023-07-05 16:09
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum/259?planning-poker) with Zenhub @ashneverdawn @ebma @TorstenStueber

**Comment by ebma** [comment] 2023-07-06 08:10
I would consider this ticket a duplicate of #250. We should close one of them.

**Comment by TorstenStueber** [comment] 2023-07-07 05:18
I propose that we close this ticket here as the other one is older.

**Closed** 2023-07-07 07:17 UTC
