### ISSUE TITLE
Update runtimes to polkadot-v0.9.42

### ISSUE THREAD

**Issue by b-yap** [pendulum-chain/pendulum#303] opened 2023-08-24 13:27 UTC
All dependencies should be upgraded to v0.9.42. 

Todo:
1. The following dependencies should be updated to v0.9.42:
    * [cumulus](https://github.com/paritytech/cumulus/tree/polkadot-v0.9.42)
    * [substrate](https://github.com/paritytech/substrate/tree/polkadot-v0.9.42)
    * [polkadot](https://github.com/paritytech/polkadot/tree/release-v0.9.42)
    * [orml](https://github.com/open-web3-stack/open-runtime-module-library/tree/polkadot-v0.9.42)
2. For the other external dependencies:
    * update https://github.com/pendulum-chain/bifrost -> compare our own branch `polkadot-v0.9.40-farming-add-currencyid-generic` and [bifrost's](https://github.com/bifrost-finance/bifrost/tree/bifrost-v0.9.80). 
      *  only the `farming` lib needs to be updated. Update the other packages if necessary.
      *  the extra generic is **_ours_** and should not be removed. See [this commit ](https://github.com/pendulum-chain/bifrost/commit/5e93473c124ebf22fb8d2ef0cd640797a6e9a8ba).
   * update https://github.com/pendulum-chain/Zenlink-DEX-Module -> compare our own branch `polkadot-v0.9.40-protocol` and [zenlink's](https://github.com/zenlinkpro/Zenlink-DEX-Module/tree/polkadot-v0.9.42).
      * only the `protocol` lib needs to be updated. Update the other packages if necessary.
   * update the parachain-staking pallet -> compare our own branch to KILT's.
      * read the changes from [the notion page](https://www.notion.so/satoshipay/23-06-09-KILT-s-changes-69165f2c982f422e9cad28e7a8322b10). Possible migration is required.
      * KILT's already at v0.9.43; but the [old PR](https://github.com/KILTprotocol/kilt-node/pull/527) can be used as reference.
3.  update spacewalk to v0.9.42

**Comment by TorstenStueber** [comment] 2023-12-16 18:15
Closing this ticket as it is actually a duplicate of https://github.com/pendulum-chain/tasks/issues/158

**Closed by TorstenStueber** 2023-12-16 18:15 UTC
